---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deps090
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: s090
    spec:
      containers:
      - name: cons090
        image: jbossacr.azurecr.io/jboss-fuse-7-tech-preview/fuse-eap-openshift:v1
        ports: 
        - containerPort: 9990
