apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dep_s090
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: s090
    spec:
      containers:
      - name: con_s090
        image: jbossacr.azurecr.io/jboss-fuse-7-tech-preview/fuse-eap-openshift:v1
        
---
apiVersion: v1
kind: Service
metadata:
  name: svc_s090
  labels:
        app: s090
spec:
  type: LoadBalancer
  ports:
  - port: 9991
  selector:
    app: dep_s090
